_1. Менеджер пакетов pip. Мотивация использования. Основные \
команды: install, list, show, freeze, uninstall. Работа с зависимостями Python-проекта._

##### Менеджер пакетов pip. Мотивация использования: 
pip — стандартный менеджер пакетов Python, позволяющий устанавливать, обновлять и удалять библиотеки, а также управлять зависимостями проекта. Он упрощает работу с внешними модулями, обеспечивает контроль версий и автоматически разрешает зависимости.
##### Основные команды:
- 1. ```pip install numpy``` - установка пакета. 
    2. ``` pip install -r requirements.txt ``` - Установка из requirements.txt 
    3. ``` pip install git+https://github.com/username/repository.git ``` - Установка из Git-репозитория 
    4. ``` pip install https://example.com/path/to/archive.zip ``` - Установка из архива по URL, если пакет доступен в виде .zip или .tar.gz 
    5. ``` pip install ./local_package_folder # путь к папке с setup.py```- Установка локального пакета
    6. ``` pip install -e git+https://github.com/user/repo.git#egg=package_name ``` - Режим разработки (-e / --editable), полезно, если нужно изменять код пакета "на лету"
- 1. ```pip list # Все пакеты```  - вывод списка установленных пакетов.
    2. ```pip list --outdated # Только устаревшие```
- ```pip show numpy``` - информация о конкретном пакете (версия, зависимости, расположение).
- ``` pip freeze > requirements.txt ``` - фиксация зависимостей в формате для requirements.txt
- ``` pip uninstall numpy``` - Удаление пакета
##### Работа с зависимостями Python-проекта:
- Создание виртуального окружения: \
\
``` python -m venv venv          # Создание ``` \
```source venv/bin/activate     # Активация (Linux/macOS)``` \
```venv\Scripts\activate        # Активация (Windows) ```

- Файл requirements.txt \
\
Формат файла: \
``` пакет==версия``` \
```другой_пакет>=минимальная_версия``` \
Пример: \
``` Flask==2.3.2``` \
```pandas>=1.5.0 ``` \
Установка: \
``` pip install -r requirements.txt ``` 
- Разрешение конфликтов \
\
Если пакеты требуют разные версии зависимостей, pip пытается найти совместимую комбинацию. \
В сложных случаях помогает ```pip check```


_2. Виртуальное окружение. Мотивация использования. Основы \
работы с виртуальным окружением с помощью venv._

##### Виртуальное окружение. Мотивация использования:
- Изоляция зависимостей \
\
Разные проекты могут требовать разные версии одних и тех же пакетов. Виртуальное окружение позволяет избежать конфликтов.

- Воспроизводимость \
\
Фиксирует версии пакетов, чтобы проект работал одинаково на разных машинах.

- Чистота системы \
\
Пакеты устанавливаются только в окружение проекта, а не глобально в систему.

##### Основы работы с виртуальным окружением с помощью venv:
```python -m venv venv_name  # Создаёт папку с окружением``` \
\
Активация: \
\
```venv_name\Scripts\activate``` - __Windows__ \
```source venv_name/bin/activate``` - __Linux/macOS__ \
\
Деактивация: \
\
``` deactivate ``` \
\
Управление зависимостями:

- Установка пакетов (только в текущее окружение): \
``` pip install requests ```
- Фиксация версий: \
```pip freeze > requirements.txt```  
- Восстановление окружения на другой машине: \
```pip install -r requirements.txt ``` 

Пример: \
\
``` python -m venv venv  # Создание окружения ``` \
```source venv/bin/activate  # Активация (для Linux/macOS)``` \
```pip install -r requirements.txt  # Установка зависимостей ``` 

Важные нюансы:
- Не добавляйте ```venv``` в Git (добавьте в ```.gitignore```). 
- Всегда активируйте окружение перед работой с проектом.
- Используйте ```requirements.txt``` для переноса проекта. \
Команда для проверки активации: \
``` which python  # Должен показывать путь внутри venv ```


_3. NumPy. Мотивация использования. Пример задачи, для решения 
которой целесообразно использовать NumPy._

##### NumPy. Мотивация использования:
NumPy — фундаментальная библиотека для научных вычислений в Python. \
\
__Ключевые преимущества:__ 
- _Эффективность_: Оптимизированные массивы (ndarray) работают быстрее обычных списков Python. Высокая скорость за счет низкоуровневых оптимизаций. (Интеграция с C и Fortran)
- _Удобство_: Богатый набор функций для операций с матрицами, линейной алгебры, статистики и др.
- _Интеграция_: Совместимость с другими научными библиотеками (SciPy, Pandas, Matplotlib).
##### Пример задачи, для решения которой целесообразно использовать NumPy:
__Задача__: Вычисление скалярного произведения векторов.

Решение без NumPy:

In [1]:
def dot_product(a, b):
    return sum(x * y for x, y in zip(a, b))

a = [1, 2, 3]
b = [4, 5, 6]
print(dot_product(a, b))  # 1*4 + 2*5 + 3*6 = 32

32


Решение с NumPy:

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # 32

32


__Почему NumPy лучше?__
- Код короче и читаемее.
- Операция выполняется в 10–100 раз быстрее для больших массивов.
- Поддержка многомерных массивов и сложных операций (например, умножение матриц).

__Когда использовать NumPy?__
- Работа с большими массивами данных.
- Математические операции (линейная алгебра, статистика).
- Машинное обучение

_4. Массивы NumPy. Отличие массивов NumPy от списков Python: 
строгая типизация элементов, хранение элементов в памяти._

1. __Типизация элементов__

- Списки Python: \
\
Могут содержать элементы разных типов (гетерогенные). Например, в одном списке можно хранить целые числа, строки и объекты одновременно:

In [5]:
py_list = [1, "текст", 3.14, True]  # Корректно

- Массивы NumPy: \
\
Все элементы массива должны быть одного типа (гомогенные). При создании массива разные типы приводятся к общему:

In [8]:
np_array = np.array([1, 2.5, 3])  # Все элементы станут float64
print(np_array.dtype)  # → float64

float64


Преобразование в случае смешении типов происходит по следующим правилам: \
\
Если ```str + любой другой тип```, то все элементы сводятся к ```str``` \
Если ```float + int/bool -> float``` \
Если ```int + bool -> int``` \
\
В случае явного указания типа через ```dtype``` NumPy либо преобразует их с потерей информации, либо выдаст ошибку:

In [ ]:
# Попытка сохранить строку как число → ValueError
arr = np.array(["текст", 1, 2.5], dtype=np.float64)
print(arr)

2. __Организация хранения в памяти__

- Списки Python: \
\
Хранят ссылки на объекты в разных участках памяти. Каждый элемент требует дополнительной памяти для хранения информации о типе и других служебных данных.

- Массивы NumPy: \
\
Данные хранятся в непрерывном блоке памяти как единый двоичный поток. Это позволяет эффективно использовать кеш процессора и оптимизирует вычисления.

3. __Производительность операций__

- Списки Python: \
\
Операции выполняются медленнее, так как для каждого элемента нужно проверять тип и выполнять дополнительные действия.

- Массивы NumPy: \
\
Операции векторизованы и выполняются на низком уровне (на C), что дает значительный прирост скорости.

4. __Размер и изменяемость__

- Списки Python: \
\
Размер может динамически изменяться, добавление и удаление элементов выполняется эффективно.

- Массивы NumPy: \
\
Размер фиксируется при создании. Для изменения размера нужно создавать новый массив, что может быть затратно по памяти.



_5.Основные способы создания массивов NumPy: функции для создания массивов NumPy из объектов Python, функции для \
создания массивов NumPy с нуля._

##### Функции для создания массивов NumPy из объектов Python

1. Из списка (list)

In [ ]:
arr = np.array([1, 2, 3])  # 1D массив
matrix = np.array([[1, 2], [3, 4]])  # 2D массив

2. Из кортежа (tuple)

In [ ]:
arr = np.array((1, 2, 3))  # Аналогично списку

3. Из других итерируемых объектов

In [ ]:
arr = np.array(range(5))  # [0, 1, 2, 3, 4]

##### Функции для создания массивов NumPy с нуля.

1. Массивы с заполнением 
- ```zeros()``` - массив из нулей:

In [ ]:
np.zeros(5)  # [0., 0., 0., 0., 0.]
np.zeros((2, 3))  # 2x3 матрица нулей

- ```ones()``` - массив из единиц:

In [ ]:
np.ones(4)  # [1., 1., 1., 1.]

- ```full()``` - массив с заданным значением:

In [ ]:
np.full((2, 2), 7)  # [[7, 7], [7, 7]]

2. Последовательности
- ```arange()``` - аналог ```range()```:

In [ ]:
np.arange(5)  # [0, 1, 2, 3, 4]
np.arange(1, 10, 2)  # [1, 3, 5, 7, 9]

- ```linspace()``` - линейно распределенные значения:

In [ ]:
np.linspace(0, 1, 5)  # [0., 0.25, 0.5, 0.75, 1.]

3. Специальные массивы
- ```eye()``` - единичная матрица:

In [ ]:
np.eye(3)  # 3x3 единичная матрица

- ```diag()``` - диагональная матрица:

In [ ]:
np.diag([1, 2, 3])  # [[1,0,0], [0,2,0], [0,0,3]]

4. Случайные массивы

In [ ]:
np.random.rand(3)  # 3 случайных числа [0,1)
np.random.randn(2, 2)  # 2x2 нормальное распределение
np.random.randint(0, 10, size=5)  # 5 целых чисел [0,10)

5. Особые случаи
- пустые массивы

In [ ]:
np.empty(3)  # Массив без инициализации (значения - "мусор")

_6.Основные атрибуты массивов NumPy. Различные виды 
индексации массивов NumPy._

##### Основные атрибуты массивов NumPy
1. ```ndim``` — количество измерений (осей) массива.

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)  # Вывод: 2

2


2. ```shape``` — размеры массива, представленные в виде кортежа. Например, для матрицы из n строк и m столбцов ```shape``` будет ```(n, m)```.

In [14]:
print(a.shape)  # Вывод: (2, 3)

(2, 3)


3. ```size``` — общее количество элементов в массиве, равное произведению всех элементов кортежа ```shape```.

In [15]:
print(a.size)  # Вывод: 6

6


4. ```dtype``` — тип данных элементов массива.

In [16]:
print(a.dtype)  # Вывод: int64

int64


5. ```itemsize``` — размер каждого элемента массива в байтах.

In [ ]:
print(a.itemsize)  # Вывод: 8

6. ```nbytes``` — общее количество байт, занимаемое массивом.

In [ ]:
print(a.nbytes)  # Вывод: 48

7. ```T``` — транспонированный массив (строки становятся столбцами и наоборот).

In [ ]:
print(a.T)
# Вывод:
# [[1 4]
#  [2 5]
#  [3 6]]

8. ```flat``` — итератор, позволяющий перебирать все элементы массива.

In [ ]:
for element in a.flat:
    print(element, end=" ")  # Вывод: 1 2 3 4 5 6

9. ```real``` и ```imag``` — возвращают действительную и мнимую части элементов массива, соответственно, если массив содержит комплексные числа.

In [ ]:
complex_array = np.array([1 + 2j, 3 + 4j])
print(complex_array.real)  # Вывод: [1. 3.]
print(complex_array.imag)  # Вывод: [2. 4.]

##### Различные виды индексации массивов NumPy

1. Индексация с помощью целых чисел


In [ ]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b[1, 0])  # Вывод: 3

2. Индексация с помощью срезов (slicing)

In [ ]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(d[1:, :2])  # Вывод: [[4 5]
                  #          [7 8]]

3. Индексация с использованием отрицательных индексов

In [ ]:
f = np.array([[1, 2], [3, 4], [5, 6]])
print(f[-1, -1])  # Вывод: 6

4. Булевая индексация

Используется для фильтрации элементов массива:


In [ ]:
g = np.array([10, 20, 30, 40, 50])
mask = g > 30
print(g[mask])  # Вывод: [40 50]

5. Индексация с использованием массивов индексов

In [ ]:
h = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(h[indices])  # Вывод: [10 30 50]

6. Индексация с использованием структурированных массивов

Если массив имеет именованные поля, можно обращаться к ним по имени:

In [ ]:
i = np.array([(1, 2), (3, 4), (5, 6)], dtype=[('a', np.int32), ('b', np.int32)])
print(i['a'])  # Вывод: [1 3 5]

7. Индексация с использованием итератора ```flat```

In [ ]:
j = np.array([[1, 2], [3, 4], [5, 6]])
for element in j.flat:
    print(element, end=" ")  # Вывод: 1 2 3 4 5 6

__Примечание:__
- При использовании срезов создается представление исходного массива, а не его копия. Это означает, что изменения в срезе отразятся на исходном массиве. Чтобы создать независимую копию, используйте метод ```.copy()```.

_7. Управление размерами массивов NumPy: методы reshape и flatten, 
объект newaxis._


1. Изменение формы массива (```reshape```) \
Метод reshape создает новый массив с другой формой, не изменяя исходные данные.


In [ ]:
arr = np.arange(12)  # [0, 1, 2, ..., 11]
matrix = arr.reshape(3, 4) # 3 строки × 4 столбца
print(matrix)
"""
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
"""

Автоматическое вычисление размерности:

In [ ]:
arr.reshape(3, -1)  # -1 означает "вычислить автоматически"

2. Преобразование в одномерный массив (```flatten```, ```ravel```) 

```flatten()```: 
- Создает копию данных
- Всегда возвращает 1D массив

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
flat = matrix.flatten()  # [1, 2, 3, 4]

```ravel()```:
- Возвращает представление {т.е. не копию} (где возможно)
- Более эффективен по памяти

In [ ]:
flat_view = matrix.ravel()  # [1, 2, 3, 4]

3. Добавление осей (```newaxis```)

Объект np.newaxis позволяет добавлять новые оси к массиву:

In [ ]:
arr = np.array([1, 2, 3])

# Преобразование в вектор-столбец (2D)
col_vector = arr[:, np.newaxis]
"""
[[1]
 [2]
 [3]]
"""

arr_3d = arr[np.newaxis, :, np.newaxis]
print(arr_3d.shape)  # (1, 3, 1)

__Примечание__:
- ```reshape``` может вернуть представление или копию в зависимости от расположения данных в памяти
- ```newaxis``` не копирует данные, только изменяет представление
- Для гарантированного копирования используйте ```.copy()```



_8. Понятие векторизованных операций в NumPy. Основные виды 
векторизованных операций. Различия между операторной и \
функциональной формой векторизованных операций._

1. Понятие векторизованных операций
Векторизованные операции — это вычисления, выполняемые над целыми массивами без явных циклов. Они реализованы на низкоуровневых языках (C/Fortran).\
Пример:

In [ ]:
# Списки Python (медленно)
a = [1, 2, 3]
b = [4, 5, 6]
result = [x + y for x, y in zip(a, b)]  # [5, 7, 9]

# NumPy (векторизованно)
a_np = np.array([1, 2, 3])
b_np = np.array([4, 5, 6])
result_np = a_np + b_np  # ndarray([5, 7, 9])

<class 'numpy.ndarray'>


2. Основные виды векторизованных операций
- Арифметические операции \
Поэлементные операции с массивами одинаковой формы:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Сложение: [5, 7, 9]
print(a * b)  # Умножение: [4, 10, 18]
print(a ** 2) # Квадрат: [1, 4, 9]

- Логические операции \
Поэлементное сравнение:

In [ ]:
print(a > 2)   # [False, False, True]
print(a == b)  # [False, False, False]

- Математические функции \
Векторизованные версии математических функций:

In [ ]:
print(np.sin(a))       # Синус: [0.841, 0.909, 0.141]
print(np.log(a + 1))   # Натуральный логарифм
print(np.exp(a))       # Экспонента

- Агрегации \
Операции по всему массиву:

In [ ]:
print(np.sum(a))      # Сумма: 6
print(np.mean(b))     # Среднее: 5.0
print(np.max(a - b))  # Максимум разности: -1

3. Операторная и функциональная форма векторизованных операций в NumPy
- Операторная форма \
Использует стандартные математические операторы (+, -, *, / и др.) для работы с массивами. \
\
Характеристики: 
    - Использует стандартные математические операторы (+, -, *, / и др.) для работы с массивами.
    - Автоматически применяет broadcasting

    Ограничения:
    - Не поддерживает дополнительные параметры (например, вывод в существующий массив)
    - Ограниченный набор операций

In [19]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Арифметические операции
sum_arr = a + b       # [5, 7, 9]
prod_arr = a * b      # [4, 10, 18]

# Логические операции
mask = a > 2          # [False, False, True]

# Со скалярами
scaled = a * 10       # [10, 20, 30]

- Функциональная форма \
Использует функции из модуля NumPy (```np.add()```, ```np.multiply()``` и др.). \
\
Характеристики:

    - Более гибкая и мощная 
    - Поддерживает дополнительные параметры 
    - Позволяет явно контролировать процесс вычислений

    Преимущества:
    - Поддержка сложных сценариев вычислений
    - Возможность оптимизации памяти (через параметр ```out```)

In [ ]:
# Эквиваленты операторной формы
sum_func = np.add(a, b)          # [5, 7, 9]
prod_func = np.multiply(a, b)    # [4, 10, 18]

# Расширенные возможности
result = np.empty_like(a)
np.add(a, b, out=result)         # Результат записывается в существующий массив

# Специальные операции
np.cumsum(a)                     # Накопленная сумма: [1, 3, 6]
np.logical_and(a > 1, b < 6)     # Логическое И: [False, True, False]